server:
  port: 8080

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: GOOGLE-CLIENT-ID
            client-secret: GOOGLE-CLIENT-SECRET
            scope: email, profile
          github:
            client-id: YOUR_GITHUB_CLIENT_ID
            client-secret: YOUR_GITHUB_CLIENT_SECRET
            scope: user:email
#          microsoft:
#            client-id: YOUR_MICROSOFT_CLIENT_ID
#            client-secret: YOUR_MICROSOFT_CLIENT_SECRET
#            scope: openid, profile, email
# Disable JWT validation for development - we'll use our custom filter instead
#      resourceserver:
#        jwt:
#          issuer-uri: https://accounts.google.com
#          jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs
  datasource:
    url: jdbc:h2:mem:finance_db
    driverClassName: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true
      path: /h2-console
  sql:
    init:
      mode: always
    schema-locations: classpath:schema.sql
logging:
  level:
    root: INFO
    com.code.truck.finances: DEBUG
    org.springframework.jdbc.core.JdbcTemplate: DEBUG
    org.springframework.security: DEBUG